esphome:
  name: poc-pico-w
  friendly_name: Proof of Concept - Pico W

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "IWDPt7SLlv9DyNFTEIK92bcSMWiwEaTbEu1BVlqo6bE="

ota:
  - platform: esphome
    password: "09872458262078f33c0f81317bc96d13"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Proof of Concept - Pico W"
    password: "smdxNZ0h2Uiw"

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

# Expose momentary pushbutton switch
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP  # Enables internal pull-up resistor (switch is GPIO pin to ground)
      inverted: False
    name: "Push Button | Pin-12"
    filters: # For switch debouncing
      - delayed_on: 50ms
      - delayed_off: 50ms

# Configure output pins
output:
  - platform: rp2040_pwm # rp2040_pwm allows for effects. (On ESP32 this needs to be 'ledc')
    pin: GPIO16
    id: gpio_16_output
  - platform: rp2040_pwm
    pin: GPIO18
    frequency: 1000 Hz
    id: gpio_18_output

# Configure the LEDs to show up as controllable lights in Home Assistant
light:
  - platform: monochromatic
    name: "LED on Pin-16"
    output: gpio_16_output
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
  - platform: monochromatic
    name: "LED on Pin-18"
    output: gpio_18_output
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
